# Generated by Django 3.2.9 on 2021-11-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_dt', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.TextField()),
            ],
        ),
    ]
